[build]
  command = "npm run build"
  publish = "out"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/submit-model"
  to = "/.netlify/functions/submit-model"
  status = 200
  force = true
  
[build.environment]
  NODE_VERSION = "18" 